export type Experience = {
  exp_id: string;
  user_id: string;
  exp_name: string;
  exp_category: string;
  exp_type: string;
  willing_travel: 'no' | 'yes';
  willing_message: string;
  exp_date: 'no' | 'yes';
  exp_start_date: string;
  exp_end_date: string;
  exp_start_time: string;
  exp_end_time: string;
  language: string;
  exp_summary: string;
  exp_describe: string;
  describe_location: string;
  exp_duration: string;
  exp_creator: string;
  creator_presence: 'yes';
  creator_presence_1?: string | null;
  services: string;
  min_age_limit: string;
  max_age_limit: string;
  min_guest_limit: string;
  max_guest_limit: string;
  amount: string;
  handicap_accessible: 'no' | 'yes';
  handicap_description: string;
  activity_level: string;
  exp_mode: string;
  online_type: string;
  clothing_recommendations: string;
  pet_allowed: 'no' | 'yes';
  is_available: '0' | '1';
  is_cancel: string;
  guest_bring: string;
  is_agree: 'no' | 'yes';
  is_exp_duration?: string | null;
  weeks: string;
  selected_date: string;
  time_slots: string;
  upload_video_url: string;
  cover_img: string;
  images: string;
  username: string;
  userImage: string;
  latitude: string;
  longitude: string;
  block_dates: string;
  created_at: string;
  exp_duration_hours: string;
  exp_duration_minutes: string;
};

export type NearbyExp = {
  category_name: string;
  expId: '0' | '1';
  experience_name: string;
  exp_mode: string;
  amount: string;
  image: string;
  username: string;
  cover_img: string;
  userImage: string;
};
