export const categoryList = [
  { text: 'All' },
  { text: 'Adventure' },
  { text: 'Wellness' },
  { text: 'Food & Drink' },
  { text: 'Wing(wo)men' },
  { text: 'Lgbtq+' },
  { text: 'Arts and Culture' },
  { text: 'Sports' },
  { text: 'Family Friendly' },
  { text: 'Socials' },
  { text: 'Creativity' },
  { text: 'Designers' },
  { text: 'Trips & Tours' },
  { text: 'Entertainment' },
  { text: 'Volunteer' },
  { text: 'Something Different' },
  { text: 'Pet Meet' },
  { text: 'Apprentice' },
  { text: 'Nature and Outdoors' },
  { text: 'Dating' },
  { text: 'Events' },
];
